language: csharp
solution: Repository.Mongo.sln
install:
  - nuget restore Repository.Mongo.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release Repository.Mongo.sln
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./Repository.Mongo.Tests/bin/Release/Repository.Mongo.Tests.dll
